# Set shell
# Check if fish exists before setting it as default shell
if-shell '[ -x /usr/bin/fish ]' 'set-option -g default-shell /usr/bin/fish'

source-file ~/.config/tmux/tmux.conf.movements
source-file ~/.config/tmux/tmux.conf.keybinds
source-file ~/.config/tmux/tmux.conf.cosmetics
source-file ~/.config/tmux/tmux.conf.copymode

set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Remove delay when pressing esc
set -s escape-time 0
set-option -g renumber-windows on
