# Set shell
set-option -g default-shell /usr/bin/fish

# Pane navigation
bind -n M-Left if-shell '[ "$(tmux display -p "#{pane_at_left}")" = "0" ]' {select-pane -L} {previous-window}
bind -n M-Right if-shell '[ "$(tmux display -p "#{pane_at_right}")" = "0" ]' {select-pane -R} {next-window}
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Vim movements
bind -n M-h if-shell '[ "$(tmux display -p "#{pane_at_left}")" = "0" ]' {select-pane -L} {previous-window}
bind -n M-l if-shell '[ "$(tmux display -p "#{pane_at_right}")" = "0" ]' {select-pane -R} {next-window}
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Resize pane using Alt + Shift + Arrow Keys
bind -n M-S-Left  resize-pane -L 
bind -n M-S-Right resize-pane -R
bind -n M-S-Up    resize-pane -U
bind -n M-S-Down  resize-pane -D

# Alt+number to switch to corresponding window
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9
bind -n M-0 select-window -t :0

# Remap prefix
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes 
bind h split-window -h
bind v split-window -v

set -g mouse on

# Enter copy mode with vi keys
bind-key Space copy-mode

# Exit copy mode with i
bind -T copy-mode-vi i send-keys -X cancel

# Start selection with 'v' and copy with 'y'
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Paste with p (like Vim's p)
bind-key p paste-buffer

# For Wayland:
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded!"

# Function: On new window, split based on terminal width

bind n run-shell ' \
         tmux new-window; \
         width=$(tmux display -p "#{window_width}"); \
         if [ "$width" -gt 150 ]; then \
         tmux split-window -h; \
         tmux resize-pane -x $((width / 2 + 25)); \
         elif [ "$width" -gt 120 ]; then \
         tmux split-window -h; \
         tmux resize-pane -x $((width * 66 / 100)); \
         fi'


# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Remove delay when pressing esc
set -s escape-time 0


# Cosmetics

# Status bar
set -g status-style "bg=black,fg=green"

# Set the pane border color
set-option -g pane-border-style 'fg=black'
set-option -g pane-active-border-style 'fg=black'

# Pane settings
set -g status-left ''
set -g status-right '[#S][#(whoami)@#H]'
set -g window-status-format '#I-#W'
set -g window-status-current-format '[#I-#W]'
