theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
true-color = true
scrolloff = 1
shell = ["/usr/bin/fish" , "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.file-picker]
hidden = false

[keys.normal]
Z = { Q = ":quit!", Z = ":x" }
X = ["extend_line_up", "extend_to_line_bounds"]
